services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: employee-portal-backend:latest
    container_name: employee-portal-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
