name: Checkmarx SAST Scan

on:
  push:
    branches: [ main, 'feature/**' ]
  pull_request:
    branches: [ main ]

jobs:
  checkmarx-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkmarx CxFlow Action
        uses: checkmarx-ts/checkmarx-github-action@v1.0
        with:
          project: ${{ github.repository }}
          team: '/CxServer/SP/Company/TeamA'
          checkmarx_url: ${{ secrets.CHECKMARX_URL }}
          checkmarx_username: ${{ secrets.CHECKMARX_USERNAME }}
          checkmarx_password: ${{ secrets.CHECKMARX_PASSWORD }}
          checkmarx_client_secret: ${{ secrets.CHECKMARX_CLIENT_SECRET }}
          incremental: true
          break_build: false
          scanners: sast
          bug_tracker: GITHUBPULL
          params: --namespace=${{ github.repository_owner }} --repo-name=${{ github.event.repository.name }} --branch=${{ github.ref }}
