name: CI with Snyk

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk:
    name: Snyk Vulnerability Check
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin' # or 'zulu', 'adopt', 'oracle' as per your preference

      # Install Snyk CLI
      - name: Install Snyk CLI
        run: npm install -g snyk

      # Run Snyk to test for vulnerabilities
      - name: Run Snyk Test
        env:
          SNYK_TOKEN: b55f74fe-aeeb-4267-b261-ac433fd882fa # Use the Snyk token
        run: snyk test --all-projects

      # Optionally monitor the project with Snyk
      - name: Monitor with Snyk
        env:
          SNYK_TOKEN: b55f74fe-aeeb-4267-b261-ac433fd882fa
        run: snyk monitor --all-projects
